#!/bin/bash


export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=jackman

. /usr/bin/gettext.sh

/usr/bin/echo "--$(date) alsa_remove--" >> /var/log/alsa/add.log


jackuser=$(ps -p `pidof jackdbus | cut -d ' ' -f1` -o user=)
jackhome=$(eval /usr/bin/echo ~$jackuser)
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u $jackuser)/bus"

if [[ ! -z $1 ]]; then
    /usr/bin/echo "arg: $1" >> /var/log/alsa/add.log
    CARD=$(grep -o -P '[0-9]*' <<< "$1" | head -1)
    DISPLAY=":0"
fi

if [ ! -z $CARD ]; then
	currentcard="$(cat $jackhome/.config/jack/conf.xml | grep device | grep -o -P '[0-9]' | head -1)"
	currentdevice="$(cat $jackhome/.config/jack/conf.xml | grep device | grep -o -P '[0-9]' | tail -n +2 | head -1)"
        currentname="$(cat /proc/asound/cards | grep "$currentcard \[" | grep -o -P '[^-]*' | tail -1 | sed -e 's/^[[:space:]]*//g' -e 's/[[:space:]]*\$//g')"

	
	if [[ $currentcard -eq $CARD ]]; then
	
            msg="`eval_gettext \"Removed card \\\${currentcard}. Trying to switch master...\"`"
            su $jackuser - -c "/usr/bin/kdialog --passivepopup \"$msg\" -display \":0\" 10 --title \"$(gettext "Audio Interface")\" --icon audio-card || \
            /usr/bin/zenity --notification --text \"$msg\" --display \":0\" --title \"$(gettext "Audio Interface")\" --window-icon audio-card || \
            /usr/bin/echo \"$msg\""

            cns="$(su $jackuser - -c '/usr/bin/jack_lsp -c')"
            IFS=',' read -r -a cons <<< "${cns//$'\n'/,}"
            
            /usr/bin/su $jackuser - -c "/usr/bin/jack_control stop" &

            if [[ $(grep audio <<< $(id $jackuser -Gn)) ]]; then
                /usr/bin/su $jackuser - -g audio -c "DBUS_SESSION_BUS_ADDRESS=\"$DBUS_SESSION_BUS_ADDRESS\" /usr/bin/jackman -fb\"${currentname},${currentdevice}\"" >> /var/log/alsa/add.log 2>&1
            else
                /usr/bin/su $jackuser - -c "DBUS_SESSION_BUS_ADDRESS=\"$DBUS_SESSION_BUS_ADDRESS\" /usr/bin/jackman -fb\"${currentname},${currentdevice}\"" >> /var/log/alsa/add.log 2>&1
            fi
            
            for ((i=0; i<${#cons[@]}; i++)); do
                    firstchar=${cons[$i]:0:1}
                    cons[$i]=$(echo "${cons[$i]}" | sed -e 's/^[[:space:]]*//g' -e 's/[[:space:]]*\$//g')
                    whitespace=$(printf '\n\t ')
                    case "$firstchar" in
                        *[!$whitespace]*) master="${cons[$i]}"
                            #/usr/bin/echo "master \"$master\"..."
                            ;;
                        *) /usr/bin/su $jackuser - -c "/usr/bin/jack_connect \"${cons[$i]}\" \"$master\"">/dev/null 2>&1
                            #/usr/bin/echo "connecting \"${cons[$i]}\" to \"$master\"";;
                    esac
            done
            
        else
        #only kill alsa_in and alsa_out for this card
            proclines=$(ps ax | grep -P "alsa_in.*hw:$CARD")
            while read -r line; do
                /usr/bin/kill -9 $(grep -o -P '[0-9]*' <<< "$line" | head -1) & disown
            done <<< "$proclines"
             
	fi;
fi
