#!/bin/bash

/usr/bin/echo "--$(date) jackman_udev_plug--" >> /var/log/jackman.log

while [[ -z $jackuser ]]; do
    jackuser=$(ps -p `pidof jackdbus | cut -d ' ' -f1` -o user=)
    [[ -z $jackuser ]] && [[ ! $USER = "root" ]] && jackuser=$USER
    [[ -z $jackuser ]] && jackuser=$(/usr/bin/users | cut -d ' ' -f 1)
    [[ -z $jackuser ]] && /usr/bin/sleep 5
done

export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u $jackuser)/bus"

jackhome=$(eval /usr/bin/echo ~$jackuser)

hotplug=$(grep -o -P '(?<=hotplug=).*' ${jackhome}/.config/jackman.conf)

if [[ ! -z $1 ]]; then
    dev="$1"
    /usr/bin/echo "arg: $1" >> /var/log/jackman.log
    ID_MODEL=$(/usr/bin/udevadm info ${dev//-/\/} | grep "ID_MODEL=" | rev | cut -d"=" -f 1 | rev)
    DEVNAME=$(/usr/bin/udevadm info ${dev//-/\/} | grep "DEVNAME=" | rev | cut -d"=" -f 1 | rev)
fi
DISPLAY=":0"

if [[ ! -z $ID_MODEL ]]; then

    if [[ $hotplug = "false" ]] || [[ $hotplug = "0" ]]; then
        exit 0
    fi

    /usr/bin/echo "Device: $ID_MODEL,$DEVICE" >> /var/log/jackman.log
    thisuser=$(/usr/bin/id -un)
    /usr/bin/echo "this user is \"${thisuser}\". jack user is \"${jackuser}\"" >> /var/log/jackman.log
    if ( [[ -z $thisuser ]] || [[ ! $thisuser == $jackuser ]] ); then
        /usr/bin/echo "running with su" >> /var/log/jackman.log
        if [[ $(grep audio <<< $(id $jackuser -Gn)) ]]; then
            /usr/bin/su $jackuser - -g audio -c "DBUS_SESSION_BUS_ADDRESS=\"$DBUS_SESSION_BUS_ADDRESS\" /usr/bin/jackman -n\"$DEVNAME\" -m\"$ID_MODEL\" -v " >> /var/log/jackman.log 2>&1
        else
            /usr/bin/su $jackuser - -c "DBUS_SESSION_BUS_ADDRESS=\"$DBUS_SESSION_BUS_ADDRESS\" /usr/bin/jackman -n\"$DEVNAME\" -m\"$ID_MODEL\" -v " >> /var/log/jackman.log 2>&1
        fi
        if ! /usr/bin/su $jackuser - -c '/usr/bin/jack_control status'; then exit 1; fi
    else
        /usr/bin/echo "su not neccessary" >> /var/log/jackman.log 
        /usr/bin/jackman >> /var/log/jackman.log 2>&1
        if ! /usr/bin/jack_control status ; then exit 1; fi
    fi
else
    /usr/bin/echo "no device given..." >> /var/log/jackman.log 
    if ( [[ -z $thisuser ]] || [[ ! $thisuser == $jackuser ]] ); then
        /usr/bin/echo "running with su" >> /var/log/jackman.log
        if [[ $(grep audio <<< $(id $jackuser -Gn)) ]]; then
            /usr/bin/su $jackuser - -g audio -c "/usr/bin/jackman -vk" >> /var/log/jackman.log 2$
        else
            /usr/bin/su $jackuser - -c "/usr/bin/jackman -vk" >> /var/log/jackman.log 2>&1
        fi
        if ! /usr/bin/su $jackuser - -c '/usr/bin/jack_control status'; then exit 1; fi
    else
        /usr/bin/echo "su not neccessary" >> /var/log/jackman.log
        /usr/bin/jackman -k >> /var/log/jackman.log 2>&1
        if ! /usr/bin/jack_control status ; then exit 1; fi
    fi

fi

